language: node_js
sudo: false
node_js:
  - "stable"
cache:
  directories:
    - node_modules
install:
  - npm install
script:
  - npm test
notifications:
  email:
    on_success: change
    on_failure: change