language: node_js
sudo: false
node_js:
  - "stable"
cache:
  directories:
    - node_modules
install:
  - npm install
script:
  - npm test
notifications:
  email:
    on_success: change
    on_failure: change
deploy:
  provider: heroku
  api_key: $HEROKU_API_KEY
  app: iot-repository-app
  on:
    branch: master